#!/bin/sh

# sqltest - fast parser testing using sqlite database.
# Type sqltest --help for usage info.
# Copyright (C) 2004-2016 Jaroslaw Staniek <staniek@kde.org>

apppath=`realpath $0`
app=`basename $apppath`
[ $# -lt 1 ] && echo "Usage: $app <sqlite-database-name> \"<sql-statement>\" [-v] [other_options]" && \
 echo " -v    Verbose mode" && exit 1

dbname=$1
shift

sql=$1
shift

verbose=0
if [ "$1" = "-v" ] ; then
	verbose=1
	shift
fi

temp=`mktemp /tmp/$app.XXXXXX`

./kdbfeaturestest --test parser sqlite "$dbname" "$sql" $* 2> $temp || \
	cat $temp && test "$verbose" -eq 1 && cat $temp

rm -f $temp
