#!/bin/sh
# Generates CMakeLists.txt and code for HeadersTest.

builddir=$1
me=generate_HeadersTest.sh
if [ ! -d "$builddir" ] ; then
    echo "Usage: $me <proper_KDb_builddir>"
    exit 1
fi

srcdir=`pwd`
echo $srcdir

cat <<EOT > CMakeLists.txt
# Generated by $me
# WARNING! All changes made in this file will be lost!

# Test if all headers can be included individually.
# This is a compile-time test.

add_executable(
HeadersTest
HeadersTest.cpp
EOT

files=`ls -1 "$builddir/src/kdb" | grep -v \.h\$`
files="$files kdb_export.h kdb_version.h config-kdb.h"

for f in $files; do
fname=${f}HeaderTest.cpp
    cat <<EOT > $fname
#include <$f>
EOT
    echo $fname >> CMakeLists.txt
done

cat <<EOT >> CMakeLists.txt
)

target_link_libraries(
  HeadersTest
  KDb
)
EOT
