/* config-kdb.h. Generated by cmake from config-kdb.h.cmake */

#ifdef BUILD_TESTING
/* Export symbols for testing */
#  define KDB_TESTING_EXPORT KDB_TESTING
#else
#  define KDB_TESTING_EXPORT
#endif
