#ifndef KDB_CONFIG_P_H
#define KDB_CONFIG_P_H

/* config-kdb-private.h. Generated by cmake from config-kdb-private.h.cmake */

/*! @file config-kdb-private.h
    Private KDb configuration (build time)
*/

//! @def KDB_EXPRESSION_DEBUG
//! @brief Defined if debugging for expressions is enabled
#cmakedefine KDB_EXPRESSION_DEBUG

//! @def KDB_DRIVERMANAGER_DEBUG
//! @brief Defined if debugging for the driver manager is enabled
#cmakedefine KDB_DRIVERMANAGER_DEBUG

//! @def KDB_TRANSACTIONS_DEBUG
//! @brief Defined if debugging for database transactions is enabled
//! @since 3.1
#cmakedefine KDB_TRANSACTIONS_DEBUG

//! @def KDB_TABLESCHEMACHANGELISTENER_DEBUG
//! @brief Defined if debugging of the KDbTableSchemaChangeListener class is enabled
//! @since 3.1
#cmakedefine KDB_TABLESCHEMACHANGELISTENER_DEBUG

//! @def KDB_QUERYSCHEMA_DEBUG
//! @brief Defined if debugging of the Debugging of the QuerySchema class is enabled
//! @since 3.2.0
#cmakedefine KDB_QUERYSCHEMA_DEBUG

//! @def KDB_SQLPARSER_DEBUG
//! @brief Defined if debugging of the SQL parser is enabled
//! @since 3.2.0
#cmakedefine KDB_SQLPARSER_DEBUG

#endif
